name: Nexus
description: "network for execution of unidentified suspects"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  provider: ^6.1.2
  google_fonts: ^6.3.1
  go_router_builder: ^3.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  result_dart: ^2.0.0
  result_command: ^2.0.0
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.2
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  lucid_validation: ^1.3.1
  web: ^1.1.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  jwt_decode: ^0.3.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  overlay_support: ^2.1.0
  mask_text_input_formatter: ^2.9.0
  file_selector: ^1.0.4
  file_selector_web: ^0.9.4+2
  flutter_dropzone: ^4.2.1
  http_parser: ^4.1.2
  dropdown_search: ^6.0.2
  flutter_native_splash: ^2.4.7
  permission_handler: ^12.0.1
  web_browser_detect: ^2.2.0
  http: ^1.6.0
  universal_html: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.4.5
  json_serializable:
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon fore.png"
  adaptive_icon_monochrome: "assets/icon/mono.png"


  web:
    generate: true
    image_path: "assets/icon/icon fore.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"


flutter_native_splash:
  web: true
  android: true
  ios: true

  background_image: "assets/icon/background.png"
  image: "assets/icon/logo.png"
  branding: "assets/icon/branding.png"

  background_image_dark: "assets/icon/background.png"
  image_dark: "assets/icon/logo.png"
  branding_dark: "assets/icon/branding.png"

  android_12:
    color: "#1565C0"
    image: "assets/icon/android_logo.png"
    branding: "assets/icon/android_branding.png"








flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - .env
