name: nexus_multiplatform
description: "network for execution of unidentified suspects"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  provider: ^6.1.2
  google_fonts: ^6.3.1
  go_router_builder: ^3.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  result_dart: ^2.0.0
  result_command: ^2.0.0
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.2
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  lucid_validation: ^1.3.1
  web: ^1.1.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  jwt_decode: ^0.3.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  overlay_support: ^2.1.0
  mask_text_input_formatter: ^2.9.0
  file_selector: ^1.0.4
  file_selector_web: ^0.9.4+2
  flutter_dropzone: ^4.2.1
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.4.5
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - .env
